
## MangoHud Profile Presets

[profile0]
# Only battery icon
battery

[profile1]
# FPS and battery icon
battery
fps

[profile2]
# FPS, battery icon, wattage, CPU and GPU usages
battery
fps
gpu_power
cpu_stats
gpu_stats

[profile3]
# FPS, battery icon, wattage, CPU and GPU usages & frametime graph
battery
fps
gpu_power
cpu_stats
gpu_stats
frametime
graph
